#pragma once

enum gdt_selectors {
    GDT_SELECTOR_KERNEL_CODE = 0x08,
    GDT_SELECTOR_KERNEL_DATA = 0x10,
    GDT_SELECTOR_USER_CODE = 0x18,
    GDT_SELECTOR_USER_DATA = 0x20,
    GDT_SELECTOR_TSS = 0x28
};
